server:
  port: ${SERVER_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/vendas}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace

service:
  mock: false

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /documentation
